spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerceDB
    username: postgres
    password: M@l3kgere
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # can be 'validate', 'create', or 'none' depending on your needs
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
